name: uchar_ketmon
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  logger: ^1.1.0
  provider: any
  shared_preferences: any
  hive: ^2.0.5
  lottie: ^2.2.0
  hive_flutter: any
  flutter_any_logo: any
  url_launcher: any
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf

